Fix mismatch between expected props expected by Image component and props received via Site Editor
vtex-apps/store-image pull request #15
Opened 2020-05-08 19:12 UTC by victorhmp

#### What does this PR do?

There was a mismatch between the Link type defined by `vtex.native-types`
and the one being expected as props by the Image component.

A new `newTab` property was added and is now supported by the component,
this should enable users to correctly configure links to open in new tabs.

#### How to test it?

Go into this [Workspace](https://slotsplayground--storecomponents.myvtex.com/admin/cms/site-editor) and try updating the link attributes in the first ImageList image using the Site Editor.

<img width="255" alt="Screen Shot 2020-05-08 at 16 11 41" src="https://user-images.githubusercontent.com/27777263/81440551-a3cbc480-9146-11ea-9764-fce05c7fd237.png">

The image below is the result of the configuration above

<img width="475" alt="Screen Shot 2020-05-08 at 16 08 18" src="https://user-images.githubusercontent.com/27777263/81440273-24d68c00-9146-11ea-9809-f10814cb6936.png">

#### Describe alternatives you've considered, if any. \*

Considered just copying the original type definition from `vtex.native-types` and change the `newTab` property name to `openNewTab`, but that would defeat the purpose of `vtex.native-types`, so I went with this solution :)

2020-05-08 19:15 UTC, klzns requested changes

2020-05-08 19:15 UTC, klzns commented on react/Image.tsx
> +  const shouldOpenLinkInNewTab = link?.newTab ?? link?.openNewTab
Comment referencing the other comment?

2020-05-11 18:21 UTC, Klynger commented on react/Image.tsx
> +      target={shouldOpenLinkInNewTab ? '_blank' : ''}
I don't think you should pass an empty string to target, maybe is better to pass `'_self'` or `undefined`
```suggestion
      target={shouldOpenLinkInNewTab ? '_blank' : undefined}
```

2020-05-11 19:33 UTC, Klynger approved these changes

2020-05-12 19:08 UTC, iaronaraujo approved these changes

2020-05-13 13:49 UTC, klzns approved these changes

2020-05-14 15:13 UTC, merged