Improving usability by other apps
vtex-apps/store-image pull request #32
Opened 2021-01-28 20:05 UTC by icazevedo

#### What problem is this solving?

This PR moves all types to a single file on the root of the `react` folder so they can be used by other apps. It also exports CSS Handles embedded within `Image` component to allow other apps to extend its functionality.

At last, it fixes schema properties' titles when they're imported by other app's schema.

#### How to test it?
[Workspace](https://icaromedia5--storecomponents.myvtex.com/)

#### Screenshots or example usage:

<img width="429" alt="Screen Shot 2021-01-28 at 17 01 56" src="https://user-images.githubusercontent.com/8127610/106192135-8a622100-618a-11eb-9eed-8c3d784df80c.png">

<img width="361" alt="Screen Shot 2021-01-28 at 17 01 45" src="https://user-images.githubusercontent.com/8127610/106192182-9817a680-618a-11eb-8d6a-c521713ea635.png">

#### Related to / Depends on

Related to [store-media#2](https://github.com/vtex-apps/store-video/pull/2)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/aSZSj0mT8f6tW/giphy.gif)

2021-01-28 20:08 UTC, klzns requested changes
Move types of props next to their components and import them in ImageTypes

2021-01-28 20:59 UTC, igorbrasileiro approved these changes

2021-01-28 21:02 UTC, vitorflg approved these changes

2021-01-29 13:06 UTC, klzns approved these changes

2021-01-29 17:21 UTC, merged