add phone image prop
vtex-apps/store-image pull request #57
Opened 2021-10-11 19:52 UTC by IncognitaDev

#### What problem is this solving?

This prop alows to use other image for phone size.  

#### How to test it?

just add the block in your theme and pass phoneImage prop

[Workspace](https://sudambeef--agenciaeplus.myvtex.com/)

#### Screenshots or example usage:

desktop
![image](https://user-images.githubusercontent.com/48053804/136847573-0e8f0674-ffb7-4298-8f8f-e771b973ddf5.png)

mobile / tablet
![image](https://user-images.githubusercontent.com/48053804/136847627-3d69cb1b-1c2d-4c6c-b53c-894e0727b911.png)

phone
![image](https://user-images.githubusercontent.com/48053804/136847662-c3062afe-7669-4a1c-86c7-6a3cdc11d273.png)

obs: is just test images.

#### Describe alternatives you've considered, if any.

use Responsive layout can be usefull but this is more work to the client.

2021-10-18 16:45 UTC, igorbrasileiro commented on react/modules/imageAsList.tsx
> +const getResponsiveImage = (device: string, image: string, mobileImage: string,phoneImage: string) => {
```suggestion
interface ResponsiveImageParams {
  device: string
  image: string
  mobileImage: string
  phoneImage: string
}
const getResponsiveImage = ({ device, image, mobileImage, phoneImage }: ResponsiveImageParams) => {
```

2021-10-18 16:45 UTC, igorbrasileiro commented on store/interfaces.json
> +      "$ref": "app:sudambeef.store-image#/definitions/Image"
Fix this interface.

2021-10-18 16:45 UTC, igorbrasileiro commented on store/interfaces.json
> +          "$ref": "app:sudambeef.store-image#/definitions/Images"
Add `vtex` back.

2021-10-18 16:48 UTC, igorbrasileiro requested changes
Great job, overall. 
Can you lint all files? Go to the root folder, install the npm packages, then run `yarn lint`.
Also, I've left some code suggestions.

2021-10-18 16:48 UTC, igorbrasileiro commented on store/interfaces.json
> +          "$ref": "app:sudambeef.store-image#/definitions/Images"
Add `vtex` back.

2021-10-18 16:48 UTC, igorbrasileiro commented on store/interfaces.json
> +          "$ref": "app:sudambeef.store-image#/definitions/Images"
Add `vtex` back.

2021-10-18 16:48 UTC, igorbrasileiro commented on store/interfaces.json
> +      "$ref": "app:sudambeef.store-image#/definitions/Image"
Add `vtex` back.

2021-10-18 16:48 UTC, igorbrasileiro commented on store/contentSchemas.json
> +            "title": "admin/editor.image-list.images.mobileImage.title",
This isn't a mobile image. Can you add a new entry for this message?

2021-10-21 17:57 UTC, camilavcoutinho requested changes

2021-10-21 17:57 UTC, camilavcoutinho commented on messages/bg-BG.json
> +  "admin/editor.image-list.images.phoneImage.title": "изображение на мобилен телефон",
```suggestion
  "admin/editor.image-list.images.phoneImage.title": "Изображение за телефон",
```

2021-10-21 17:57 UTC, camilavcoutinho commented on messages/it-IT.json
> +  "admin/editor.image-list.images.phoneImage.title": "Immagine per telefonino",
```suggestion
  "admin/editor.image-list.images.phoneImage.title": "Immagine per cellulari",
```

2021-10-21 17:57 UTC, camilavcoutinho commented on messages/ja-JP.json
> +  "admin/editor.image-list.images.phoneImage.title": "携帯電話用画像",
```suggestion
  "admin/editor.image-list.images.phoneImage.title": "電話用画像",
```

2021-10-21 17:57 UTC, camilavcoutinho commented on messages/ko-KR.json
> +  "admin/editor.image-list.images.phoneImage.title": "휴대폰용 이미지",
```suggestion
  "admin/editor.image-list.images.phoneImage.title": "휴대폰의 이미지",
```

2021-10-21 17:57 UTC, camilavcoutinho commented on messages/ro-RO.json
> +  "admin/editor.image-list.images.phoneImage.title": "Imagini pentru telefon mobil",
```suggestion
  "admin/editor.image-list.images.phoneImage.title": "Imagine pentru telefon mobil",
```

2021-10-21 19:23 UTC, camilavcoutinho approved these changes

2021-11-02 14:31 UTC, igorbrasileiro approved these changes

2021-11-25 04:54 UTC, pachecovit commented
Aprovem o PR do cara! Essa feature está sendo de grande importancia para a comunidade VTEX hehehhuhe

2024-08-26 17:44 UTC, closed without merging