Add srcMobile prop to image component
vtex-apps/store-image pull request #75
Opened 2023-02-24 01:25 UTC by agnaldopsfilho

#### What problem is this solving?

The "image" block does not accept properties to define different images for mobile and desktop devices. When we want to do that, we need to use other components like the responsive-layout, which makes the development process and changes in the site editor difficult.
To resolve this I created a new property "srcMobile" for the image component to be able to apply responsiveness to images. This change will not affect any component in production since the "src" prop was not removed and if there is no "srcMobile" prop, the "src" image that will be applied to the mobile. I also added the translations of the new property in the messages

#### How to test it?

1. Go to [Workspace](https://imagesrcmobile--corelabiz.myvtex.com)
2. In the site editor inspect the main home image

#### Screenshots or example usage:

Before (the same image was used on desktop and mobile) :
![image](https://user-images.githubusercontent.com/70102023/221066096-39b2baa2-5e3f-4959-a720-419e32a583c9.png)

After (it is possible to use different images for desktop and mobile):
![image](https://user-images.githubusercontent.com/70102023/221066669-b9583e29-5ad2-430f-82c0-cfad3ad9f9bd.png)
Code example:
![image](https://user-images.githubusercontent.com/70102023/221066846-15b4e769-ddad-43db-a194-a95283702efd.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/cMPdlbcUKl3xkMCyD3/giphy.gif)

2023-02-28 14:06 UTC, sheilagomes requested changes

2023-02-28 14:06 UTC, sheilagomes commented on messages/pt.json
> +  "admin/editor.store-image.mobileSrc.title": "Imagem para mobile",
```suggestion
  "admin/editor.store-image.mobileSrc.title": "Imagem para dispositivos móveis",
```

2023-02-28 14:06 UTC, sheilagomes commented on messages/bs-BA.json
> +  "admin/editor.store-image.mobileSrc.title": "crwdns133880:0crwdne133880:0",
This whole file can be removed as it is not used anymore

2023-03-01 11:46 UTC, sheilagomes approved these changes

2023-10-03 12:55 UTC, agnaldopsfilho commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [x]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2024-08-26 17:44 UTC, closed without merging